algolia/algoliasearch-client-php

composer.json
src/AlgoliaSearch/Client.php
src/AlgoliaSearch/Index.php
src/AlgoliaSearch/Version.php
tests/AlgoliaSearch/Tests/BasicTest.php

No more filesystem access for this version header.
- also fix some minor coding std (un-used var, missing return)
- also add mbstring as composer dependency - help to detect not compatible PHP installations (mbstring is not installed by default in CentOs and all other "yum" based systems).

Fix #26: move the version to a PHP const for performances

---

src/AlgoliaSearch/Client.php

Added support for custom curl options like CURLOPT_PROXY, CURLOPT_PROXYPORT...
On construct you can specified an array with curl options:
```php
$options = [
'curloptions' => [
CURLOPT_PROXY => 'tcp://1.2.3.4:80',
CURLOPT_PROXYPORT => '8080',
CURLOPT_PROXYUSERPWD => 'USERNAME:PASSWORD',
//...
]
];
$client = new Client(
'app-id',
'admin_api_key',
null,
$options
);
```
if a bad curl option is given, proper exceptions are thrown : 
* InvalidArgumentException when not an array
* OutOfBoundsException when not a valid curl option

Proxy support

---

src/AlgoliaSearch/Index.php

Changed split to explode() as per PHP7 spec.

PHP7 Removed "split" Function

---

src/AlgoliaSearch/Client.php
src/AlgoliaSearch/ClientContext.php

Implements the functionality from: https://www.algolia.com/doc/faq/analytics/will-the-analytics-still-work-if-i-perform-the-search-through-my-backend
fixes https://github.com/algolia/algoliasearch-client-php/issues/44
I haven't added tests since I cant configure them to run locally...

Add forwared ip and user token headers

---

.gitignore
.php_cs
README.md
composer.json
phpunit.xml.dist
src/AlgoliaSearch/AlgoliaException.php
src/AlgoliaSearch/Client.php
src/AlgoliaSearch/ClientContext.php
src/AlgoliaSearch/Index.php
src/AlgoliaSearch/IndexBrowser.php
src/AlgoliaSearch/PlacesIndex.php
src/AlgoliaSearch/Version.php
tests/AlgoliaSearch/Tests/AccessTest.php
tests/AlgoliaSearch/Tests/AlgoliaSearchTestCase.php
tests/AlgoliaSearch/Tests/BasicTest.php
tests/AlgoliaSearch/Tests/BatchTest.php
tests/AlgoliaSearch/Tests/BrowseIndexTest.php
tests/AlgoliaSearch/Tests/BrowseTest.php
tests/AlgoliaSearch/Tests/ClearIndexTest.php
tests/AlgoliaSearch/Tests/DeleteIndexTest.php
tests/AlgoliaSearch/Tests/DeleteTest.php
tests/AlgoliaSearch/Tests/FunctionTest.php
tests/AlgoliaSearch/Tests/GetTest.php
tests/AlgoliaSearch/Tests/InitPlacesTest.php
tests/AlgoliaSearch/Tests/ListIndexesTest.php
tests/AlgoliaSearch/Tests/LogTest.php
tests/AlgoliaSearch/Tests/MoveIndexTest.php
tests/AlgoliaSearch/Tests/SecurityTest.php
tests/AlgoliaSearch/Tests/SettingsTest.php
tests/AlgoliaSearch/Tests/URLEncodeTest.php

Started correcting some docblocks, and refactored some small pieces.
Please note that I have not a deep understanding of the behaviour of this client yet, so please tell me if some changes may break something. Hope the tests will catch problems though.
Do you guys see any interest in these adjustments if they do not introduce BC issues?
Please react on the changes so I can adjust the PR.
Fixes #32

Refactoring, mainly docblocks and CS.

---

src/AlgoliaSearch/Client.php

It fixes the documentation of  `addUserKey` and some typos.

Fix PHPDoc

---

src/AlgoliaSearch/Client.php

With the current code, the custom headers were always ignored because of the wrong format generated by the array_merge:
0 => string 'X-Algolia-Application-Id: ME'
1 => string 'X-Algolia-API-Key: TOP-SECRET'
2 => string 'Content-type: application/json'
'X-Forwarded-For' => string '159.253.242.85'
But in the documentation of curl it's written that only array are allowed, the associative **keyStr => val** array are not allowed.
> 	An array of HTTP header fields to set, in the format array('Content-type: text/plain', 'Content-length: 100')

Fix custom headers

---

src/AlgoliaSearch/Index.php
tests/AlgoliaSearch/Tests/DisjunctiveFacetingTest.php

You can add to algoliasearch.php:
```
$client = new AlgoliaSearch\Client('AJ0P3S7DWQ', '%%API_KEY%%');
$index = $client->initIndex('best_buy');
var_dump($index->search('test', ['facetFilters' => ["type:Wireless speakers", "brand:Beats by Dr. Dre", ["categories:Audio", 'categories:TV & Home Theater']], 'facets' => [], 'disjunctiveFacets' => ['type', 'brand', 'categories']]));
```
To run some test on the best buy instantsearch demo

implement better disjunctive faceting

---

src/AlgoliaSearch/Index.php
tests/AlgoliaSearch/Tests/GetTest.php

Implement attributesToRetrieve for getObjects method

---

.travis.yml
algoliasearch.php
src/AlgoliaSearch/Client.php
src/AlgoliaSearch/ClientContext.php
src/AlgoliaSearch/FailingHostsCache.php
src/AlgoliaSearch/FileFailingHostsCache.php
src/AlgoliaSearch/InMemoryFailingHostsCache.php
tests/AlgoliaSearch/Tests/ClientContextTest.php
tests/AlgoliaSearch/Tests/ClientTest.php
tests/AlgoliaSearch/Tests/FailingHostsCacheTestCase.php
tests/AlgoliaSearch/Tests/FileFailingHostsCacheTest.php
tests/AlgoliaSearch/Tests/InMemoryFailingHostsCacheTest.php
tests/AlgoliaSearch/Tests/global_functions_stubs.php
tests/benchmark.php

We abstracted an interface for the failed hosts retrieval so that users can easily choose their caching strategy based on what is best according to their environment.
By default we push the new File Based cache strategy, but if the tmp directory is not writable, we fallback to the in memory strategy.
User can provide an implementation of FailingHostsCache as a replacement of this strategy.
Because of the current design of the Client, the FailingHostsCache implementation needs to be provided at Client initialization because that is where the ClientContext is instantiated and during that instantiation we need to rotate the hosts.
Regarding the BC static to non static, given it has only been available in 1 version and was only used internally + wasn't even called statically, I think we are …

Keep state between processes

---

tests/AlgoliaSearch/Tests/FunctionTest.php

The default connection timeout is now 1s but the keep-alive test still assumed it was 2.
Locally my tests fail because of this.
BTW I'm not seing how this tests actually tests keep alive, any insight @maxiloc ?

test(keep-alive): update the connection timeout

---

composer.json

Composer offers a separate autoload property for development environment. This is ideal to load tests if they are in a separate namespace, especially if the tests aren't distributed to the production environments (as specified in the `.gitattributes` file).

Autoload tests only on dev environment

---

src/AlgoliaSearch/Index.php
src/AlgoliaSearch/SynonymBrowser.php
tests/AlgoliaSearch/Tests/SynonymsExportTest.php

This class allows you to easily browse (or export) all your synonyms, just like you browse the records of your index.
I would like feedback on how the array of a single synonym should be formatted. Currently, it's as follow:
```
Array
(
[type] => altCorrection1
[word] => Avenue
[corrections] => Array
(
[0] => Av
[1] => Ave
)
[objectID] => avenue
)
```

Introduce SynonymsBrowser class

---

algoliasearch.php
src/AlgoliaSearch/Index.php
src/AlgoliaSearch/Iterators/AlgoliaIterator.php
src/AlgoliaSearch/Iterators/RuleIterator.php
src/AlgoliaSearch/Iterators/SynonymIterator.php
src/AlgoliaSearch/SynonymIterator.php
tests/AlgoliaSearch/Tests/RulesExportTest.php
tests/AlgoliaSearch/Tests/SynonymsExportTest.php

Most of the Iterator code was extracted to `AlgoliaIterator` and both synonyms and rules rely extend this class.
Rules are limited to 500 by default because the API will currently reject 1000. The python API clients will update to 500 too.

Introduce RuleIterator

---

src/AlgoliaSearch/Client.php
tests/AlgoliaSearch/Tests/InitPlacesTest.php
tests/AlgoliaSearch/Tests/MoveIndexTest.php
tests/AlgoliaSearch/Tests/PlacesIndexTest.php

Please note that for internal reason when scopedCopyIndex doesn't include `settings`, the engine will notre create the index. You have to create it manually before or after.

Introduce Scoped Copy Index

---

composer.json
tests/AlgoliaSearch/Tests/AlgoliaSearchTestCase.php
tests/AlgoliaSearch/Tests/ClientContextTest.php
tests/AlgoliaSearch/Tests/ClientTest.php
tests/AlgoliaSearch/Tests/DeleteTest.php
tests/AlgoliaSearch/Tests/FailingHostsCacheTestCase.php
tests/AlgoliaSearch/Tests/FileFailingHostsCacheTest.php
tests/AlgoliaSearch/Tests/FunctionTest.php
tests/AlgoliaSearch/Tests/JsonTest.php

I've added `PHPUnit 6` support.
I just need to bump PHPUnit version to [`^4.8.35`](https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-4.8.md#4835---2017-02-06) and [`^5.7`](https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-5.7.md#570---2016-12-02), that support the `PHPUnit\Framework\TestCase` namespace.

Support PHPUnit 6

---

tests/AlgoliaSearch/Tests/BasicTest.php
tests/AlgoliaSearch/Tests/FunctionTest.php
tests/AlgoliaSearch/Tests/GetTest.php
tests/AlgoliaSearch/Tests/MultiClusterManagementTest.php
tests/AlgoliaSearch/Tests/SearchFacetTest.php
tests/AlgoliaSearch/Tests/SecurityTest.php
tests/AlgoliaSearch/Tests/SettingsTest.php

I've refactored some tests, using:
- `assertCount` instead of `count` function;
- `assertNotNull` instead of comparison with `null` keyword;
- `assertNotEquals` instead of comparisons `!=`;
- `assertGreaterThan` for mathematical comparions;
- `assertArrayHasKey` and `assertArrayNotHasKey` instead of `isset` function.

Refactoring tests

---

tests/AlgoliaSearch/Tests/SecurityNewNamingTest.php

Those tests weren't executed because of our naming convention.
@maxiloc @rayrutjes @JanPetr Do you know if it was on purpose?

SecurityNewNaming tests were never executed

---

src/AlgoliaSearch/Client.php
src/AlgoliaSearch/Index.php
tests/AlgoliaSearch/Tests/SecurityNewNamingTest.php

Currently if you do
```php
$client->addApiKey([
'acl' => ['search'],
'validity' => 24*60*60,
]);
```
The validity will not be set because the current method overrides it with default value of the second parameter.

Allow user to pass fully detailled key to `addApiKey`

---

src/AlgoliaSearch/ClientContext.php
tests/AlgoliaSearch/Tests/InitPlacesTest.php

Currently, if places is enabled, we set special read hosts but not write hosts. `appID-dsn` and such don't exists, we also need to set special hosts.
`places-dsn.algolia.net` will allow access to a read-only app, `places.algolia.net` must be used instead.
Note that you can't index data into a Places app but you may want to create API keys.

Set write hosts when using Places

---

src/AlgoliaSearch/Index.php

All keys should be managed using the Client class.
If you use the Index class, you'll attached the key to the index internally. They are not displayed in the dashboard and cannot be retrieve with `Client::listApiKeys()`. This is a deprecated feature, that shouldn't be used anymore.
Instead, you can create a key using `Client::addApiKey` that will be attached to the Application internally. You can add restriction on the index to achieve the same behavior.

Deprecate the use of keys on the Index class

---

README.md

This PR fixes the link of the Laravel integration on the `README.md` file. Currently, the link point to a 404 page.

Fixes Laravel Scout link

---

src/AlgoliaSearch/Index.php
tests/AlgoliaSearch/Tests/RulesTest.php

Preventing users to shoot themselves in the foot, following the issue with discovered in the Go client (see https://github.com/algolia/algoliasearch-client-go/issues/397).

fix: Prevent saving a rule with an empty objectID

---

src/AlgoliaSearch/Index.php
tests/AlgoliaSearch/Tests/BrowseIndexTest.php
tests/AlgoliaSearch/Tests/BrowseTest.php

Cursor can get very long and exceed the max url size, for that reason we always pass it in the body of the request.
Note: In case there is no params (if you use $query = null) we fallback on a GET call since the API doesn't allow empty bodies for POST.

Browse: Ensure cursor is passed in the body

---

src/AlgoliaSearch/Client.php

Hey 👋
This PR addresses a small optimization on the method `setConnectTimeout` of the class `AlgoliaSearch \Client`. 
- Improves code readability.
- Improves **performance** avoiding methods such as `version_compare` and `curl_version` if the `$this->context->connectTimeout` is less than 1.

Optimises method setConnectTimeout

---

src/AlgoliaSearch/Index.php
tests/AlgoliaSearch/Tests/IndexTest.php

Fix #369 
The parameter `$objectIDKey` only existed in the the PHP client. We decided to remove it to keep consistency with other client and ease documentation.
The signature of each method was kept for backward compatibility but should be used as if it was changed.
| Before                                                                                                     | After                                                                           |
|------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------|
| addObjects($objects, $objectIDKey = 'objectID', $requestOptions = [])                                      | addObjects($objects, …

"Remove" $objectIDKey

---

src/AlgoliaSearch/Index.php

This PR fixes `E_WARNING: Invalid argument supplied for foreach()` here : https://github.com/algolia/algoliasearch-client-php/blob/master/src/AlgoliaSearch/Index.php#L850
In some cases I don't have the `facets` key :

Fix PHP warning

---

CHANGELOG.md
src/AlgoliaSearch/Client.php
src/AlgoliaSearch/Index.php

| Need Doc update   | yes (not sure)
2 methods about taskID initially available in the `Index` moved to the `Client`. The original methods on the index still work are **not** deprecated.
```php
// New 🎉
$client->waitTask($indexName, $taskID, $timeBeforeRetry = 100, $requestHeaders = array())
$client->getTaskStatus($indexName, $taskID, $requestHeaders = array())
// Still available
$index->waitTask($taskID, $timeBeforeRetry = 100, $requestHeaders = array())
$index->getTaskStatus($taskID, $requestHeaders = array())
```
**NOTE**: The `$timeBeforeRetry` parameter is kept even if it doesn't exist in other clients. I believe it's a powerful feature.
You …

feat(client): Expose waitTask in the client

---

CHANGELOG.md
src/AlgoliaSearch/Analytics.php
src/AlgoliaSearch/Client.php
src/AlgoliaSearch/Json.php
tests/AlgoliaSearch/Tests/AnalyticsTest.php

Algolia introduced (in Beta) a new feature to create AB Test directly from your dashboard. This PR aims to make it easier to manage ABTests programatically.
I'd like to introduce a new _"first-class citizen object"_ , along with `Client` and `Index`, named `Analytics`. More method should be added to the Analytics object if we validate it.
The Analytics API doc can be found here: chttps://www.algolia.com/doc/rest-api/analytics/. 
```php
$analytics->getABTests(); // It's not called `list`, because it's paginated
$analytics->addABTest($abTestDefinition); // It's not called `save` because you can't set the abtestID …
```

Introducing AB Testing

---

src/AlgoliaSearch/Client.php

| Related Issue     | n/a
some comments
The comments imply that records will be copied if you specify a scope.
This is not the behavior I observe, and this is also not what is
documented on https://www.algolia.com/doc/rest-api/search/#copymove-index :
> Keep in mind that when you use the scopes parameter, you will no
longer be copying records (objects) but only the specified scopes.
It might have been true in the past, but it is currently not the case.

Describe actual behavior of scoped copy operation

---

autoload.php

Adding a custom autoload. If you don't use composer, you can require the new `autoload.php`.
Example:
```php
<?php
require 'lib/algolia/autoload.php'; # example path
$client  = Client::create();
```
Some older projects (WordPress, Drupal 7, and such) aren't using composer for autoloading). For v1, they rely on a file that require all the existing file: [`algoliasearch.php`](https://github.com/algolia/algoliasearch-client-php/blob/1.27.0/algoliasearch.php).
This new file sets a custom autoloader instead of requiring all the things.

Introduce custom PSR-4 autoload if not using composer

---

tests/AlgoliaSearch/Tests/RulesTest.php

| New feature?      | sort of    
Query Rules were recenlty improved to add a `enabled` flags and a `validity` attribute which takes timewindow when the rule should be active.
There is nothing to add in the PHP client but I added these attributes in the test suite, just in case.

tests(rules): Add more advanced query rules to test new attributes

---

src/Client.php
src/Index.php
src/Iterators/ObjectIterator.php
src/Iterators/RuleIterator.php
src/Iterators/SynonymIterator.php
src/RequestOptions/RequestOptions.php
src/Support/Helpers.php
src/functions.php
tests/Unit/HelpersTest.php

This Pull Request addresses a violation of PSR-1: Method names should be declared in camelCase.

Fixes PSR-1 violation on helpers methods names

---

src/Index.php
src/Interfaces/ClientConfigInterface.php
src/RetryStrategy/ApiWrapper.php
src/Support/ClientConfig.php
tests/Endpoint/ForwardToReplicasDefaultTest.php
tests/Endpoint/RequestTestCase.php
tests/Integration/AlgoliaIntegrationTestCase.php
tests/Integration/SettingsTest.php

Instead of adding so many method, I introduce a config option for default to `forwardToReplica = true` based on @nunomaduro's feedback.
This will be used this way:
```php
$client = Client::createWithConfig(['defaultForwardToReplicas' => true]);
$client->initIndex('name')->setSettings($settings); // Will be forwarded to replicas
$client->initIndex('name')->setSettings($settings, ['fowardToReplicas' => false); // Will *NOT* be forwarded 
```
~I added a method named `setSettingsWithReplicas` with basically call `setSettings` with the `forwardToReplicas` set to true (default is false).~
```php …
```

[RFC] Introduce setSettingsWithReplicas() method

---

.gitignore
CHANGELOG.md
composer.json
src/Algolia.php
src/Analytics.php
src/Cache/FileCacheDriver.php
src/Cache/NullCache.php
src/Cache/NullCacheDriver.php
src/Client.php
src/Interfaces/ClientConfigInterface.php
src/Places.php
src/RetryStrategy/ApiWrapper.php
src/RetryStrategy/ClusterHosts.php
src/RetryStrategy/Host.php
src/RetryStrategy/HostCollection.php
src/Support/ClientConfig.php
tests/Integration/FileCacheDriverTest.php

| BC breaks?        | ¯\_(ツ)_/¯   
I have added a cache mecanism. Restoring the feature that already exists in v1. The point is to store the state of Algolia hosts so if a server is down, you don't try it at every PHP request.
* Ideally, I'd like to ship a Redis driver as well. 
* We may want to add load testing.
The cache driver must implement `CacheInterface` provided by PSR-16. It makes the cache easily swappable with a lot of libraries, although it adds a dependency and makes a a bit harder to install of you don't use composer (typically WordPress or Drupal < 7).

Introduce Cache

---

CHANGELOG.md
src/Client.php
src/Config/AbstractConfig.php
src/Config/ClientConfig.php
src/Exceptions/CannotWaitException.php
src/Exceptions/TaskTooLongException.php
src/Http/Guzzle6HttpClient.php
src/Http/Php53HttpClient.php
src/Http/Psr7/BufferStream.php
src/Http/Psr7/Stream.php
src/Http/Psr7/Uri.php
src/Http/Psr7/functions.php
src/Index.php
src/Places.php
src/Response/AbstractResponse.php
src/Response/AddApiKeyResponse.php
src/Response/DeleteApiKeyResponse.php
src/Response/IndexingResponse.php
src/Response/MultipleIndexingResponse.php
src/RetryStrategy/ApiWrapper.php
tests/API/MethodConsistentConstraint.php
tests/API/PublicApiChecker.php
tests/Integration/KeysTest.php
tests/Integration/SettingsTest.php
tests/Unit/ResponseObjectTest.php

| BC breaks?        | yes if you use `is_array` on indexing response
Every indexing operations returns an object with a `wait()` method. The response from the API is **still accessible as an array**.
```php
$response = $index->saveSynonym($synonym);
$response.wait();
echo $response['objectID'];
$response = $cliebt->addApiKey();
$response.wait();
echo $response['value'];
```
It makes waiting pretty cool. It's now consistant, whether you're waiting for a new API key or a standard indexing operations.
In order to wait, I inject the client or the index inside the response. I'm afraid of the consequenses on memory consumption. 
I unset the client or index at …

Introduce ResponseObjects

---

src/RetryStrategy/ClusterHosts.php

| Bug fix?          | yes/no
| New feature?      | yes/no    
The following example didn't work, it now works:
```php
$config = new ClientConfig();
$config->setHosts(["custom.algolia.com"]); // <- pass string, array of string or array like ["host" => $priority];
$client = Client::createWithConfig($config);
```

Handle string[] for hosts in config

---

src/Client.php

Otherwise we'll have to maintain one instance per credentials tuple
Before this fix, if you call Client::get($app1, $key1) and then
Client::get($app2, $key2), the second call will return client using
credentials passed in the first call.
We volontarily choose to only allow the use of singleton via the
ALGOLIA_APP_ID and ALGOLIA_API_KEY env vars.

Singleton reads credentials from env

---

src/AlgoliaSearch/Client.php
tests/AlgoliaSearch/Tests/BasicTest.php

| Related Issue     | See #295  
This is a port of this PR https://github.com/algolia/algoliasearch-client-php/pull/295 where I edited the function to make it compatible with the upcoming v2.0.0 of the client.
Thank you @pengend for opening it, sorry it tool so long to merge.
I have cherry-picked your commit to you are still the author of the original function.

Add MultipleGetObjects

---

tests/AlgoliaSearch/Tests/AccessTest.php
tests/AlgoliaSearch/Tests/ClientContextTest.php
tests/AlgoliaSearch/Tests/FunctionTest.php
tests/AlgoliaSearch/Tests/RulesExportTest.php
tests/AlgoliaSearch/Tests/SecurityNewNamingTest.php
tests/AlgoliaSearch/Tests/SynonymsExportTest.php

* Add assertions to avoid the message about Risky tests.
* Ensure all API key created are deleted (I found 28 pages of API keys in our test app)
Note: Tests are currently failing for community PR because of little bug when checking API key index permissions.

Little tests cleanup

---

src/Index.php

| BC breaks?        | yes, removed function     
This function was meant to help with atomic reindexing, I don't think it's ready for production yet, especially since we don't have any effecient way to grab data (see #420).
We'll add this feature later.

Fresh objects is not ready for production yet

---

src/AlgoliaSearch/Index.php

| Related Issue     | n/a
Revert the behaviour of AlgoliaSearch\Index::waitTask to return the taskStatus response.
v1.27.0 removed the `return`, this is just adding it back in.

Return behaviour of Index::waitTask to pre-1.27.0

---

docs/UPGRADE-from-v1-to-v2.md
src/SearchClient.php
tests/API/client.yaml
tests/Integration/IndexManagementTest.php

| BC breaks?        | yes     
The method `listIndexes` was renamed `listIndices`, this is how it was documented: https://deploy-preview-2021--algolia-doc.netlify.com/doc/api-reference/api-methods/list-indices/
Unfortunately, I didn't change the name properly in the client.  😩 
I realized that looking at @vinkla's PR https://github.com/vinkla/laravel-algolia/pull/12

Fixed listIndices name (was still listIndexes)

---

.gitignore
src/RetryStrategy/ApiWrapper.php

| Related Issue     | 
| Need Doc update   |no
refactor detection of `json_encode()` errors
As currently written, with an empty body, the client will choose not to json_encode the body. However, if there is a previous `json_last_errror()` from any other json_encode calls during the request lifetime, the client will throw an exception, even though the error is not from _its own_ `json_encode()` call

Fix json_encode error detection

---

src/SearchIndex.php

After calling the method `reindex` on the SearchIndex class, the `replicas` setting is not preserved.
**Note**: We should consider adding tests to this method.

Keeps replicas settings after reindex

---

.travis.yml

PHP 7.3 will be out on the 6 December, and this Pull Request addresses that.

Test against PHP 7.3 on CI

---

src/Response/MultiResponse.php
src/Response/NullResponse.php
src/SearchIndex.php
tests/Unit/ResponseObjectTest.php

| Related Issue     | Fix [this](https://discourse.algolia.com/t/no-content-in-post-request-when-copying-indexes-between-aps/6645)
When sending an empty batch, the API will return a 400 error. This could happen if you passed an empty dataset to the methods or if you were sending exactly 1000, 2000, 3000... objects.
Related to #482 
`AccountClient::copyIndex` was breaking because of if you didn't have synonyms or rules, the iterators were empty.
```php
$index1->saveSynonyms($index2->browseSynonyms());
```
* If you pass an empty dataset to `saveObjects`, `saveSynonyms` or `saveRules`, you get a NullResponse (waitable) …

Introduce NullResponse for empty batches

---

src/RequestOptions/RequestOptionsFactory.php
tests/requestOptions.json

By default, all API calls have `Content-Type: application/json` header. It can be overridden via the default headers pass in the config.
The Search API doesn't require it but some other apis do (insight).

Always pass Content-Type default header

---

src/SearchClient.php
tests/Integration/MultipleIndexTest.php

`multipleBatch` should not check for objectIDs in the list of operations. Batch are different forms and don't require an objectID.
A batch can be any sort of operations, typically, to delete multiple indexes at once:
```php
$client->multipleBatch([
[
'action' => 'delete',
'indexName' => 'xx',
], [
'action' => 'delete',
'indexName' => 'yy',
]
]);
```

Remove ensureObjectID for Client::multipleBatch

---

src/Algolia.php
src/PlacesClient.php
src/SearchClient.php
src/SearchIndex.php
tests/Unit/RequestTestCase.php
tests/Unit/SearchTest.php

PHP is not a strong typed language, and some developers may enter in the mistake of passing non strings into a `search` method. E.g: In the Laravel Framework:
```php
$query = request('query'); // This may be null.
$results = Post::search($query);
```
This Pull Request addresses this cases, the `null` type is now converted to an empty string.

[2.1.2] Adds `null` resilience to search $query

---

autoload.php

Working on WordPress integration, I realized that in some cases, the required files couldn't be found. I added `__DIR__` to make sure we always require the correct path.

Fix autoloader when not using composer

---

CHANGELOG.md
src/Response/RestoreApiKeyResponse.php
src/SearchClient.php
tests/Integration/KeysTest.php

This pull request adds the `SearchClient::restoreApiKey` method.

[2.2] Adds restore api key method to search client

---

src/Iterators/AbstractAlgoliaIterator.php
tests/Integration/BrowseAndIteratorsTest.php

| Related Issue     | Fix #514   
when browsing an index (objects, rules or synonyms), the "key" (index) of the loop was never incremented.
```php
$iter = $client->initIndex('something')->browseObjects();
foreach ($iter as $key => $value) {
// without this fix, $key will always be 0
dump($key);
}
```

Fix iterator key increment

---

tests/Integration/AnalyticsClientTest.php

Test suite is not passing. This removes the ab test ensuring that the `tearDown` can remove the index correctly.

Fixes ab test avoiding `Can't delete index under ab testing` error

---

src/SearchIndex.php

I made a mistake when naming the `searchForFacetValues` method in the v2. I forgot the S at the end. The documentation is "correct" (ie use plural method name).
This PR fix the name of the method and is aliasing the wrong name to the correct name.

Fix sffv function name (plural)

---

.travis.yml

The command `composer install` is causing the following issue on travis in PHP 5.3:
```
$ composer install
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Loading composer repositories with package information
Updating dependencies (including require-dev)
PHP Fatal error:  Allowed memory size of 1610612736 bytes exhausted (tried to allocate 78 bytes) in phar:///home/travis/.phpenv/versions/5.3.29/bin/composer/src/Composer/DependencyResolver/Solver.php on line 223
PHP Stack trace:
PHP   1. {main}() /home/travis/.phpenv/versions/5.3.29/bin/composer:0
```
This happens on PHP 5.3, because composer has memory issues looking for packages compatible with PHP 5.3. This pull request removes the memory limit.

Removes memory limit on travis composer install

---

bin/install-dependencies-without-composer

If the user has a space in his root path like `/home/julien/My Projects`, the path will be broken in 2 arguments when passed to mkdir for instance.
This PR will escape space to turn the path into `/home/julien/My\ Projects`

Custom install script escapes space in root path

---

src/Algolia.php

| New feature?      | no  
| Related Issue     | [#537](https://github.com/algolia/algoliasearch-client-php/issues/537)
This pull request is related to this issue [#537](https://github.com/algolia/algoliasearch-client-php/issues/537)
The PHP client has by default implementation for http client. 
However PHP client support guzzle as http client as well. 
A customer can use guzzle but only version 6. If he use a previous version it's not supported. 
In our current implementation, the PHP Client only check if the class exist. If the version is not supported it will automatically wired. Which result to a bug. 
Since the version 4, guzzle use in their …

Fix versions not supported for guzzle http client

---

CHANGELOG.md
src/Algolia.php

With the version `v2.2.3` we have shipped code that doesn't work with old versions of PHP: `Parse error: syntax error, unexpected '[', expecting ',' or ';' `. This pull request addresses that exact same issue.
Fixes #547 .

Fixes syntax error with old php versions

---

CHANGELOG.md
src/SearchIndex.php
tests/Integration/ExistsTest.php

| Related Issue     | Fix #564  
This adds the `SearchClient::exists` method in the client. It follows the [spec](https://github.com/algolia/algoliasearch-client-specs/blob/master/features/index-exists.md) and [common test suite](https://github.com/algolia/algoliasearch-client-specs/tree/master/common-test-suite#Exists).

feat(index): add exists method

---

src/Http/Guzzle6HttpClient.php
src/Http/Php53HttpClient.php
src/RetryStrategy/ApiWrapper.php
tests/Integration/SettingsTest.php

| Related Issue     | Fix #571
At the moment, both `guzzle`|`legacy` requesters are breaking their contracts/interfaces throwing exceptions from the requesters themselves. As example, the guzzle is throwing a guzzle specific exception `cURL error 7: Failed to connect to XXXXXXXX-dsn.algolia.net port 443: Connection refused` when the host is not available using an exception specific the guzzle.
And this compromises the retry strategy as it doesn't catch exceptions from the requester, and **consequently doesn't retry in other host**.
After this change, both requesters will now always return a response from the requester, when the host …

Fixes retry strategy when hosts are unreachable

---

src/RetryStrategy/ApiWrapper.php
tests/Integration/IndexManagementTest.php

| Related Issue     | Fix #592   
Today, the logger is only used in ApiWrapper and is not injectable. It's the only class used that you can't inject. This PR makes it injectable.
If you don't inject it, we'll keep calling `Algolia::getLogger()`.

Make Logger injectable in ApiWrapper

---

CHANGELOG.md
src/SearchIndex.php
tests/Integration/RulesTest.php

This pull request fixes an issue when people get rules with empty list of consequence params from `getRule` or `browseRules` and then save them with a `saveRule` or `saveRules`.

fix: rules with empty params

---

src/SearchIndex.php

| Related Issue     | Fix #604 
Fix the error message on the `saveObjects` method

fix(auto-generate-id-message): improves wording

---

tests/Integration/InsightsClientTest.php

| Related Issue     | Fix #569 
Adds tests for `send_events`/`send_event` and add the timestamp option

chore(insights): send_events tests

---

src/SearchClient.php
tests/Integration/MultiClusterManagementTest.php

| Related Issue     | Fix #615 
This PR renames the `getTopUserId` to `getTopUserIds`. Please keep in mind that `2.6.1` is used in annotations, make sure we update this to the right version number if necessary.

fix(get-top-user-ids): rename getTopUserId to getTopUserIds

---

src/Http/Guzzle6HttpClient.php
src/RetryStrategy/ApiWrapper.php

This pull request fixes the fact that the range 1xx wasn't considered retryable.

fix(deserialization-of-continue-100): forces expect header to be false

---

tests/Integration/RulesTest.php

| Related Issue     | Fix #625 
An optional `_metadata` field has been added to the response of `getRule()`, this fixes the test

chore(rules): fix tests for new metadata field

---

.travis.yml
src/Algolia.php
src/Support/UserAgent.php
tests/Unit/UserAgentTest.php

| Related Issue     | Fix #619
Adds support for Guzzle 7, main difference being how to retrieve the guzzle version for tagging user-agent and choosing adapter. Otherwise the behaviour of the current guzzle adapter works with Guzzle 7.

chore(http): add support of guzzle 7

---

.travis.yml
CHANGELOG.md
src/RetryStrategy/ApiWrapper.php
tests/Unit/ApiWrapperTest.php

| BC breaks?        | no   
| Related Issue     | Fix #546
Automatically enable `JSON_UNESCAPED_UNICODE` option for request payload encoding.
**I've tested this on a real index an it does work as expected &mdash; the document is indexed perfectly fine**.
This is a port of #545 onto *2.x* master version. 
Reincarnation of #577 with a unit test added.

Fix - Unescaped Unicode JSON encoding

---

.circleci/config.yml

| Related Issue     | 
This updates the env variables we use before running the API key dealer.
The current variables in use are not [set by CirlceCI](https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables), which will result in failing tests for PRs from forked repositories. This is the same error as fixed in https://github.com/algolia/scout-extended/pull/258.

fix(CI): use correct env variables for forks

---

src/AnalyticsClient.php

This fix add the missing part of the url called by the stopABTest() method in the AnalyticsClient class

fix: Add missing part of the url for stopABTest() method

---

src/SearchClient.php
src/Support/Helpers.php
tests/Integration/MultipleIndexTest.php

| Related Issue     | Fix #624
This PR deals with the changes proposed in PR #637 with the following additions :
- serializeQueryParameters has been moved to Helpers class
- null coalescing operator has been changed to an old PHP version compliant ternary operator
- removed short syntax for empty array
- the MultipleIndexTest has been updated

Handling of params array in the $queries array for multipleQueries method

---

src/SearchClient.php

This adds `search()` method as an alias for the `multiplequeries()` method to align method names across all API clients.

feat: add search alias for multiple queries

---

src/Config/PersonalizationConfig.php
src/PersonalizationClient.php
src/SearchClient.php
tests/Integration/PersonalizationClientTest.php

As per our internal specification, this renames the `RecommendationClient` to `PersonalizationClient`. For backwards compatibility you'll still be able to use the `RecommendationClient` until the next major version.

chore: rename recommendation client

---

bin/install-dependencies-without-composer

| Related Issue     | Failing CI on `master`
This pins the `psr/log` package when not using composer to v1.1.4 (the latest 1.x version). We need to do this because we used `master` before, but this introduced breaking changes (v3 of the package only supports newer PHP versions).

fix: pin log dependency

---

README.md

| Related Issue     | Fixes no existing issue
The provided example used a single dimensional array as an argument for the `saveObjects()` method.
As saveObjects saves an array of objects, it generated an error.
I updated the example to use a single `saveObject()` method, which I find easier to understand as a beginner than a two-dimensional array argument for `saveObjects()`

Corrected saveObjects call example

---

src/Http/Psr7/Request.php
src/Http/Psr7/Stream.php
src/Http/Psr7/Uri.php
src/Response/AbstractResponse.php
src/Response/BatchIndexingResponse.php
src/Response/MultiResponse.php

| New feature?      | no  
| Related Issue     | Fix #701 
Added PHPDoc @returns to some methods to prevent a deprecation alert when using symfony/error-handler

Fixes deprecation alert when using symfony/error-handler

---

src/RecommendClient.php

| Related Issue     | Related to PR #704 
The ApiWrapper class was no longer imported and thus a fatal error is thrown

Fix class not found error

---

src/Http/Psr7/Response.php

This is similar to #703 . The change adds phpdoc comments to document the return types of the response class.
This should make some deprecations messages about the possibility the
parent class adds return type declarations in the future disappear.

Add phpdoc regarding return types

---

CHANGELOG.md
src/Support/Helpers.php
tests/Unit/HelpersTest.php

| Related Issue     | n/a
In this PR, we include the input string that is fed to `json_decode`, because it will help understanding issues with it.
This helper is used in a single place, to decode the response coming from Algolia. If the response is invalid, the contents of the input string is lost, making it impossible to troubleshoot the error.
Here is an example of what I am currently experiencing in my application:
`json_decode error: Control character error, possibly incorrectly encoded`
I don't think there is a way for me to troubleshoot this.

Include input string in message about invalid json

---

.circleci/config.yml
README.md
composer.json
src/Http/Psr7/BufferStream.php
src/Http/Psr7/PumpStream.php
src/Http/Psr7/Request.php
src/Http/Psr7/Response.php
src/Http/Psr7/Stream.php
src/Http/Psr7/Uri.php

This includes: 
- Changes coming from @Stoux (<3) : https://github.com/algolia/algoliasearch-client-php/pull/717
- Fixed linter
- Fixed CI
- Dropped PHP 7.2

Add support for psr/http-message ^2.0

---

bin/install-dependencies-without-composer

| Related Issue     | 
The `CURLOPT_BINARYTRANSFER` PHP constant from the Curl extension was no-op since PHP 5.1, and is deprecated in PHP 8.4. This removes the constant usage to avoid the deprecation notice in PHP 8.4 and later.
Because this constant was no-op since PHP 5.1 (circa 2005), this change has no impact.
See:
- [PHP.Watch - PHP 8.4 - Curl: CURLOPT_BINARYTRANSFER deprecated](https://php.watch/versions/8.4/CURLOPT_BINARYTRANSFER-deprecated)
- [commit](https://github.com/php/php-src/commit/fc16285538e96ecb35d017231051f83dcbd8b55b)
Fixes PHP 8.4 deprecation notice.

[PHP 8.4] Fix: Curl `CURLOPT_BINARYTRANSFER` deprecated

---

src/Http/GuzzleHttpClient.php
src/Http/Psr7/Uri.php
src/RetryStrategy/ApiWrapper.php

Since PHP 8.4, implicitly marking a parameter as nullable is deprecated.

Address PHP 8.4-specific deprecation
