README.md

This is an easier way to install that package than editing the composer.json. It'll also always pull in the latest stable version.

Use composer install to install the package

---

src/AlgoliaSearch/Index.php

Bugfix :
* Now retrieve only objectID not all object data
* Now using 1000 per package, not the default search limit (20)
Optimize :
* Optimize a little PHP
* Standard coding
* Do not wait the last call (If you have just one call, you never wait)
Sorry i can't test. You can C/C the function if you prefer and not merge..
```        
$this->client = new Client(getenv('ALGOLIA_APPLICATION_ID'), getenv('ALGOLIA_API_KEY'), null, array("cainfo" => (__DIR__ . '/../../../resources/ca-bundle.crt')));
```

Bugfix + Optimize deleteByQuery

---

.gitattributes

We don't need all these files in production.

Add .gitattributes for smaller download size

---

.travis.yml
composer.json

This is currently work in progress.

Add PHP version to composer

---

README.md

The documented example for the multiple queries doesn't actually make a request. It should be making a $client->multipleQueries($queries) request.

Adding in multipleQueries request

---

.php_cs
src/AlgoliaSearch/Client.php
src/AlgoliaSearch/ClientContext.php
tests/AlgoliaSearch/Tests/ClientContextTest.php
tests/AlgoliaSearch/Tests/FunctionTest.php
tests/AlgoliaSearch/Tests/InitPlacesTest.php

Randomize the fallback hosts on a per client instance basis.

---

.php_cs
.travis.yml
composer.json
src/AlgoliaSearch/Client.php
src/AlgoliaSearch/ClientContext.php
src/AlgoliaSearch/Index.php
src/AlgoliaSearch/PlacesIndex.php
src/AlgoliaSearch/SynonymType.php
tests/AlgoliaSearch/Tests/AccessTest.php
tests/AlgoliaSearch/Tests/BasicTest.php
tests/AlgoliaSearch/Tests/BatchTest.php
tests/AlgoliaSearch/Tests/BrowseIndexTest.php
tests/AlgoliaSearch/Tests/BrowseTest.php
tests/AlgoliaSearch/Tests/ClearIndexTest.php
tests/AlgoliaSearch/Tests/ClientContextTest.php
tests/AlgoliaSearch/Tests/DeleteIndexTest.php
tests/AlgoliaSearch/Tests/DeleteTest.php
tests/AlgoliaSearch/Tests/FunctionTest.php
tests/AlgoliaSearch/Tests/GetTest.php
tests/AlgoliaSearch/Tests/ListIndexesTest.php
tests/AlgoliaSearch/Tests/MoveIndexTest.php
tests/AlgoliaSearch/Tests/SecurityTest.php
tests/AlgoliaSearch/Tests/SettingsTest.php
tests/AlgoliaSearch/Tests/SynonymsTest.php
tests/AlgoliaSearch/Tests/URLEncodeTest.php

Due to the recent DDOS attack our dns provider faced, a lot of people were worried that they could not get to the latest version of the API Client because we stopped supporting PHP 5.3.
This PR is a POC to see if we could continue supporting PHP 5.3.

Fallback to php 5.3.

---

src/AlgoliaSearch/Index.php

Make deleteByQuery based on browse feature instead of search. Fixes #107

---

algoliasearch.php
src/AlgoliaSearch/Client.php
src/AlgoliaSearch/Index.php
src/AlgoliaSearch/Json.php
tests/AlgoliaSearch/Tests/JsonTest.php

JSON validations

---

src/AlgoliaSearch/Client.php
tests/AlgoliaSearch/Tests/BasicTest.php

Send strategy as POST attribute and not as part of URL

---

src/AlgoliaSearch/Client.php

Fix a concatenation issue

---

src/AlgoliaSearch/Client.php
src/AlgoliaSearch/ClientContext.php
src/AlgoliaSearch/Index.php
src/AlgoliaSearch/Json.php
src/AlgoliaSearch/Version.php
tests/AlgoliaSearch/Tests/AccessTest.php
tests/AlgoliaSearch/Tests/BasicTest.php
tests/AlgoliaSearch/Tests/SearchFacetTest.php
tests/AlgoliaSearch/Tests/SettingsTest.php
tests/AlgoliaSearch/Tests/VersionTest.php

I re-ran php-cs-fixer since it wasn't run since a long time.
Also I tested #133 so cherry picked it here.

Code style + more stringent cURL handle checks

---

CONTRIBUTING.md

| Q             | A
| ------------- | ---
| Doc?         | yes
This PR adds new section about run tests correctly.

Add section with informations about testing

---

src/AlgoliaSearch/Client.php
src/AlgoliaSearch/ClientContext.php
tests/AlgoliaSearch/Tests/ClientContextTest.php
tests/AlgoliaSearch/Tests/InitPlacesTest.php

See https://github.com/algolia/places/pull/401 for more context.

Make API credentials optional for Places usage

---

README.md

Hello,
I just noticed this typo in the readme, i fixed the link.
regards

fix link of contacts.json file in readme

---

src/AlgoliaSearch/Index.php
tests/AlgoliaSearch/Tests/ClientContextTest.php
tests/AlgoliaSearch/Tests/RulesTest.php

I expect the tests to fail on travis given the feature is not deployed on our testing APP ID.

feat(query-rules): add query-rules support

---

algoliasearch.php

Looks like we didn't catch this during review of #298

fix(classmap): add missing AlgoliaConnectionException.php

---

CHANGELOG.md
src/AlgoliaSearch/Version.php

Release new `SynonymIterator` and `RuleIterator`.

Release v1.22.0

---

src/AlgoliaSearch/Client.php
src/AlgoliaSearch/Index.php
src/AlgoliaSearch/IndexBrowser.php

See internal conversation for context 
https://algolia.slack.com/archives/C3742QTHT/p1499242553433222

Add $requestHeaders parameters to necessary methods

---

.travis.yml
phpunit.xml.dist
tests/AlgoliaSearch/Tests/AlgoliaSearchTestCase.php
tests/AlgoliaSearch/Tests/MultiClusterManagementTest.php
tests/AlgoliaSearch/Tests/RulesExportTest.php
tests/AlgoliaSearch/Tests/SynonymsExportTest.php

Use the Api Key Dealer to get a temporary key.
Pull request use a separated test suite, log and key operations aren't tested. They tested on `master` branch.
https://blog.algolia.com/travis-encrypted-variables-external-contributions/

Build community pull requests

---

tests/AlgoliaSearch/Tests/SearchFacetTest.php

Fix #395 
There might be more tests to update with this 🤔

Add waitTask for setSettings

---

tests/AlgoliaSearch/Tests/PlacesIndexTest.php
tests/AlgoliaSearch/Tests/SecurityNewNamingTest.php

Use dedicated PHPUnit assertions

---

src/AlgoliaSearch/Client.php
src/AlgoliaSearch/Index.php

Some cleanup and variable renaming after the recent client review

Internal cleanup

---

src/AlgoliaSearch/Version.php
tests/AlgoliaSearch/Tests/VersionTest.php

I added a "lang" suffix to differenciate clearly between the package version and the language version.

UserAgent: Add language version

---

CHANGELOG.md
src/AlgoliaSearch/Version.php

Release 1.26.0

---

src/AlgoliaSearch/Json.php

| Related Issue     | N/A
Removed debugging code added in bec782c
I'm sure this shouldn't have made it into a tagged release

Remove debugging code

---

composer.json

This pull requests updates the PHP and PHPUnit version constraints with updated syntax.
Currently the package is supporting all future versions of PHP. We only want to support versions we actually have tested. This will prevent future hickups.

Update php and phpunit version constraints

---

composer.json

| Related Issue     | N/A
This will allow developers to test the new version by specifying ^2.0 in their composer.json files.

Added 2.0-dev branch alias

---

composer.json

This Pull Requests updates the `composer.json`:
- Adds info about the package
- Leverages composer to verify extensions & requirements
- Suggests Guzzle HTTP Client implementation

Updates composer.json

---

composer.json
src/Analytics.php
src/Client.php
src/Http/Php53HttpClient.php
src/Http/Psr7/BufferStream.php
src/Http/Psr7/PumpStream.php
src/Http/Psr7/Request.php
src/Http/Psr7/Stream.php
src/Http/Psr7/Uri.php
src/Http/Psr7/UriResolver.php
src/Http/Psr7/functions.php
src/Index.php
src/Iterators/AbstractAlgoliaIterator.php
src/Places.php
src/RetryStrategy/ApiWrapper.php
src/RetryStrategy/ClusterHosts.php
src/RetryStrategy/Host.php
src/RetryStrategy/HostCollection.php
src/Support/ClientConfig.php
tests/API/PublicApiTest.php

| BC breaks?        | Not sure  
I have refactored the host management to implement the 5minutes timeout if an host is down and to reconnect to the main host as fast as possible.
Next, I'm going to add the cache on the file system to restore the state.
We need a better name for `ClusterHosts`.

Refactor retry strategy and host management

---

bin/algolia-doctor

This Pull Request adds the exit code the algolia doctor. This may be useful on CI env's.

Adds exit code to doctor

---

.travis.yml
phpunit.xml.dist
src/Client.php
tests/API/client.yaml
tests/Endpoint/CopyResourcesTest.php
tests/Endpoint/RequestTestCase.php
tests/RequestHttpClient.php

Discussed many times, I realized they weren't implemented. 😓

Introduce copySynonyms, copySettings, copyRules

---

src/RetryStrategy/ApiWrapper.php

This Pull Request improves the logging on the request adding context to every log message.
Important: **We don't log information about the body or about the headers outside of debug(testing) mode.**

Improves request cycle logging

---

.travis.yml
composer.json
src/Http/Guzzle6HttpClient.php
src/Http/HttpClientFactory.php
src/Http/Php53HttpClient.php
src/Support/UserAgent.php
tests/API/MethodConsistentConstraint.php
tests/API/PublicApiTest.php
tests/Endpoint/RequestTestCase.php
tests/Integration/AlgoliaIntegrationTestCase.php
tests/Integration/KeysTest.php
tests/Integration/MultipleIndexTest.php
tests/Integration/SettingsTest.php
tests/Unit/UserAgentTest.php

Fix Travis build

---

src/Places.php
tests/Integration/PlacesTest.php

| Bug fix?          | yes/no
| New feature?      | yes/no    
Places was added but never implemented, it's done now

Implement places

---

bin/algolia-doctor

| Related Issue     | Fix #105   
See issue #105 and #109 for original PR.
Thank you @JanPetr @rayrutjes and @lt for the original PR and ideas.

Added: doctor will check for curl AsynchDNS feat

---

src/Config/PlacesConfig.php
src/Places.php
src/PlacesClient.php
src/RetryStrategy/ClusterHosts.php
tests/Integration/PlacesTest.php

Reverts algolia/algoliasearch-client-php#461

Re-add Algolia Places

---

src/SearchClient.php

Introducing
```php
$strategy = $searchClient->getStrategy();
$searchClient->setStrategy($strategy);
```

Introduce Get/Set Strategy for Personalization

---

src/Config/AbstractConfig.php
tests/requestOptions.json

This Pull Request increases the write timeout to 30 seconds. As demanded on the docs of the retry strategy.

[2.1.1] Increases write timeout to 30s

---

.gitattributes

Remove some files from the zip generated by github. It should also be removed by composer when installing the lib.
These files are necessary for dev but shouldn't be distributed.

Remove configuration files from exported zip

---

src/Config/SearchConfig.php

This is just a refactor to remove unused code.

Removes unused wait task max retry

---

tests/Integration/AnalyticsClientTest.php

This Pull Request adds tests on AA Testing.

Adds tests concerning AA Tests

---

composer.json
src/RequestOptions/RequestOptions.php
tests/Integration/IndexingTest.php

| Related Issue     | https://github.com/algolia/algoliasearch-client-php/issues/518
This pull request address this issue : https://github.com/algolia/algoliasearch-client-php/issues/518

Add Indexing following the CTS

---

tests/Integration/IndexingTest.php

This Pull Requests makes the tests pass in PHP 5.3
Tests are not passing in PHP 5.3.

Refactors test indexing to add support to php 5.3

---

bin/algolia-doctor

| Related Issue     | https://github.com/algolia/algoliasearch-client-php/pull/486
Including composer autoloader.
> This fix is related to this issue : https://github.com/algolia/algoliasearch-client-php/pull/486 
Check if [GuzzleClient](https://packagist.org/packages/guzzlehttp/guzzle)  is available.

Fixing include composer autoloader

---

.gitignore
.php_cs.dist
.travis.yml
composer.json
src/Http/Psr7/Request.php
src/Http/Psr7/Response.php

| Related Issue     | https://github.com/algolia/algoliasearch-client-php/issues/519
This proposal adresses about **implementing a quality tool to check syntax.**
> This proposal was already discussed in https://github.com/algolia/algoliasearch-client-php/issues/519
Currently we're using [StyleCI](https://styleci.io/) to check syntax after we've committed our modification. 
Implementing [PHP-CS-Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer/tree/v2.0.0) would be the best quality tool to implement and improve our delivery because we can see all conflicts before a commit.
I've set the same configuration as …

Add phpcsfixer

---

src/Response/DeleteApiKeyResponse.php

Phpdocs within `DeleteApiKeyResponse::class`.

Fixes phpdocs within DeleteApiKeyResponse

---

src/Response/RestoreApiKeyResponse.php

Phpdocs within RestoreApiKeyResponse.

Fixes phpdocs in RestoreApiKeyResponse

---

src/Exceptions/ObjectNotFoundException.php
src/SearchIndex.php
tests/Integration/AlgoliaIntegrationTestCase.php
tests/Integration/IndexManagementTest.php
tests/Integration/SearchIndexTest.php
tests/Unit/SearchIndexTest.php

| Related Issue     | Fix #573

chore: adds unit testing relevance functions

---

src/Exceptions/ValidUntilNotFoundException.php
src/SearchClient.php
tests/Integration/SearchClientTest.php

| Related Issue     | Fix #576

feat(remaining-validity): add getSecuredApiKeyRemainingValidity method

---

src/Http/HttpClientInterface.php

Fix type information in HttpClientInterface:sendRequest

---

.travis.yml

Adds PHP7.4 in the CI, updates the Ubuntu dist as well

chore(travis): adds php7.4 support

---

src/SearchClient.php
tests/Integration/AlgoliaIntegrationTestCase.php
tests/Integration/MultiClusterManagementTest.php

| Related Issue     | Fix #586 
Adds the MCM `assignUserIDs` method and adds the CTS MCM test suite

feat(mcm): adds assignUserIDs method

---

src/SearchClient.php
tests/Integration/MultiClusterManagementTest.php

| Related Issue     | Fix #597
- adds `hasPendingMappings` method

feat: hasPendingMappings

---

tests/Integration/PersonalizationStrategyTest.php

Fixes tests to skip the 429 error

fix(personnalization-strategy): fixes flaky tests

---

.circleci/config.yml

Adds a call to the API key dealer to run external contributors' PRs

chore: change api key dealer

---

.circleci/config.yml
phpunit.xml.dist
tests/Integration/DictionaryManagementTest.php

chore: updates phpunit

---

.circleci/config.yml

chore(circleCI): fix syntax

---

src/Config/RecommendConfig.php
src/RecommendClient.php
tests/Integration/RecommendClientTest.php

This PR introduces the Recommend Client implementation

feat(recommend): add RecommendClient class

---

.circleci/config.yml

This updates the CircleCI image we use. Support for the older image will soon be dropped.

chore: move to newer CircleCI image

---

composer.json
src/Log/DebugLogger.php

| Related Issue     | Fix #692

fix: psr log

---

src/Iterators/AbstractAlgoliaIterator.php
src/Response/AbstractResponse.php
src/Response/BatchIndexingResponse.php
src/Response/MultiResponse.php

| Related Issue     | Fix #694

fix: add PHP 8.1 compatibility

---

composer.json

| Bug fix?           | yes
| New feature?      |no   
Improves compatibility with PHP8

Allow newer version of psr/simple-cache

---

.circleci/config.yml
tests/Integration/AnalyticsClientTest.php

chore: add PHP 8.1 img check

---

composer.json

Should fix: 
https://github.com/algolia/algoliasearch-client-php/issues/720

feat: change compatibility for psr/http-message
